version: "2"
services:
    web:
        build: .
        restart: always
        ports:
        - "80:80"
        - "443:443"
        depends_on:
        - mongo
    mongo:
        image: mongo
        ports:
        - "27017:27017"
